import { useState } from 'react'
import { supabase } from '@/lib/supabase'
import { studentsApi } from '@/api/students'
import { useUpdateStudent } from '@/hooks/students'
import { useUpdateSpeechScreening } from '@/hooks/screenings'
import { useToast } from '@/hooks/use-toast'
import { ProgramStatus, ServiceStatus, Screening, Student } from '@/types/database'
import { ErrorPatterns } from '@/types/screening-form'
import { SpeechEA } from './caseloadUtils'
