import { useState } from 'react'
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'
import { useToast } from '@/hooks/use-toast'
import { consentFormsApi } from '@/api/consentForms'
import { format } from 'date-fns'
import { ExternalLink, Loader2 } from 'lucide-react'
