// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qcpdfhatfdwudpnfiejy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFjcGRmaGF0ZmR3dWRwbmZpZWp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MTQ3MDAsImV4cCI6MjA2NDE5MDcwMH0.cyO_tugBVLa4DEZ8w0kxSL9PzfJd52oWk_41v5ts4oQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);