// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tvdnhcocgvuzeonejiut.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2ZG5oY29jZ3Z1emVvbmVqaXV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNDgxOTEsImV4cCI6MjA2NDcyNDE5MX0.5UL2Kxs1Y2vUBRe8qCcy-JTC4emf4p6Vo4s2qetSJYk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);